### ISSUE TITLE
Error on every weekday

### ISSUE THREAD

**Issue by elranu** [P4sca1/cron-schedule#230]
code:
      
      const cron = parseCronExpression('0 12 10 ? * THU *');
      console.log("next date: " + cron.getNextDate());

error:

      Error: Invalid cron expression: expected 5 or 6 elements.
      at K (C:\Dev\otros\nautioPupeter\node_modules\cron-schedule\src\cron-parser.ts:178:11)
      at Object.<anonymous> (C:\Dev\otros\nautioPupeter\index.ts:125:33)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Module.m._compile (C:\Dev\otros\nautioPupeter\node_modules\ts-node\src\index.ts:1371:23)
      at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
      at Object.require.extensions.<computed> [as .ts] (C:\Dev\otros\nautioPupeter\node_modules\ts-node\src\index.ts:1374:12)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
      at main (C:\Dev\otros\nautioPupeter\node_modules\ts-node\src\bin.ts:331:12)

**Comment by P4sca1** [comment]
Please see https://github.com/P4sca1/cron-schedule#cron-expression-format for the correct cron syntax.
The question mark operator is not supported (use * instead) and there can only be 5 or 6 elements (and not 7 like in your example).
